# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-03 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='soldhistory',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=4)),
                ('postcode', models.CharField(max_length=5)),
                ('suburb', models.CharField(max_length=100)),
                ('suburb_id', models.IntegerField(blank=True, max_length=11)),
                ('full_address', models.CharField(blank=True, max_length=255)),
                ('property_type', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bedrooms', models.IntegerField(blank=True, max_length=11)),
                ('bathrooms', models.IntegerField(blank=True, max_length=11)),
                ('carspaces', models.IntegerField(blank=True, max_length=11)),
                ('sold_date', models.DateField(blank=True)),
                ('agent', models.CharField(blank=True, max_length=255)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('update_date', models.DateField(auto_now_add=True)),
                ('processed_date', models.DateField(blank=True)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
