# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-03 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soldhistoryModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='soldhistory',
            table='overall_sold_history_increment',
        ),
    ]
